<?php
$lang = "en";
if(isset($_GET["lang"]) && in_array($_GET["lang"], ["en", "hy"])){
    $lang = $_GET["lang"];
}

$texts = [
    "en" => [
        // ========== MAIN TRANSLATIONS ==========
        "title" => "Developer Quiz",
        "desc" => "Test your programming knowledge!",
        "start" => "Start Game",
        "admin" => "Admin Panel",
        "quiz_finished" => "Quiz Finished",
        "great_job" => "Great job developer",
        "back_home" => "Back Home",
        "play_again" => "Play Again",
        "submit" => "Submit Quiz",
        "Admin Panel" => "Admin Panel",
        "Add New Question" => "Add New Question",
        "Question" => "Question",
        "Option A" => "Option A",
        "Option B" => "Option B",
        "Option C" => "Option C",
        "Option D" => "Option D",
        "Correct Answer (1-4)" => "Correct Answer (1-4)",
        "existing_questions" => "Existing Questions",
        "correct_answer" => "Correct answer",
        "delete" => "Delete",
        "delete_confirm" => "Are you sure you want to delete this question?",
        
        // ========== AUTH TRANSLATIONS ==========
        "login" => "Login",
        "register" => "Register",
        "logout" => "Logout",
        "username" => "Username",
        "email" => "Email",
        "password" => "Password",
        "confirm_password" => "Confirm Password",
        "already_have_account" => "Already have an account?",
        "login_here" => "Login here",
        "no_account" => "Don't have an account?",
        "register_here" => "Register here",
        "username_or_email" => "Username or Email",
        "all_fields_required" => "All fields are required",
        "username_min_length" => "Username must be at least 3 characters",
        "invalid_email" => "Invalid email address",
        "password_min_length" => "Password must be at least 6 characters",
        "passwords_not_match" => "Passwords do not match",
        "username_or_email_exists" => "Username or email already exists",
        "registration_error" => "Registration error, please try again",
        "invalid_credentials" => "Invalid username/email or password",
        "register_as_admin" => "Register as Admin",
        "first_user_admin" => "🎯 You are the first user! You will be registered as ADMIN",
        "admin_registered_success" => "Admin registered successfully!",
        "registered_success" => "Registered successfully!",
        
        // ========== TIMER TRANSLATIONS ==========
        "total_time_left" => "⏰ Total Time Left",
        "time_for_question" => "⏱️ Time for this question",
        "time_is_up" => "Time's Up",
        "timeout_message" => "Sorry, your time is up! Please try again.",
        
        // ========== PERCENTAGE & GRADES ==========
        "your_score_percentage" => "Your Score",
        "excellent" => "Excellent!",
        "very_good" => "Very Good!",
        "good" => "Good!",
        "average" => "Average",
        "poor" => "Need Improvement",
        "correct_answers" => "Correct Answers",
        "total_questions" => "Total Questions",
        "wrong_answers" => "Wrong Answers",
        
        // ========== SHUFFLE & COUNT ==========
        "questions_shuffled" => "🎲 Questions are in random order",
        "reshuffle" => "🔄 Reshuffle Questions",
        "dark_mode" => "Dark Mode",
        "light_mode" => "Light Mode",
        "select_question_count" => "Select number of questions",
        "playing_questions" => "Playing",
        "all_questions" => "All Questions",
        
        // ========== HTML QUESTIONS ==========
        "What does HTML stand for?" => "What does HTML stand for?",
        "Hyper Text Markup Language" => "Hyper Text Markup Language",
        "Home Tool Markup Language" => "Home Tool Markup Language",
        "Hyperlinks and Text Markup Language" => "Hyperlinks and Text Markup Language",
        "High Tech Modern Language" => "High Tech Modern Language",
        "Which tag is used to create a hyperlink in HTML?" => "Which tag is used to create a hyperlink in HTML?",
        "<link>" => "<link>",
        "<a>" => "<a>",
        "<href>" => "<href>",
        "<url>" => "<url>",
        "Which HTML tag is used to insert an image?" => "Which HTML tag is used to insert an image?",
        "<img>" => "<img>",
        "<table>" => "</tr>",
        "<src>" => "<src>",
        "<pic>" => "<pic>",
        "What is the correct HTML element for the largest heading?" => "What is the correct HTML element for the largest heading?",
        "<heading>" => "<heading>",
        "<h6>" => "<h6>",
        "<head>" => "<head>",
        "<h1>" => "<h1>",
        
        // ========== CSS QUESTIONS ==========
        "What does CSS stand for?" => "What does CSS stand for?",
        "Creative Style Sheets" => "Creative Style Sheets",
        "Computer Style Sheets" => "Computer Style Sheets",
        "Cascading Style Sheets" => "Cascading Style Sheets",
        "Colorful Style Sheets" => "Colorful Style Sheets",
        "Which CSS property is used to change the text color?" => "Which CSS property is used to change the text color?",
        "text-color" => "text-color",
        "color" => "color",
        "font-color" => "font-color",
        "text-style" => "text-style",
        "How do you select an element with id 'header' in CSS?" => "How do you select an element with id 'header' in CSS?",
        ".header" => ".header",
        "#header" => "#header",
        "header" => "header",
        "*header" => "*header",
        "Which CSS property controls the spacing between elements?" => "Which CSS property controls the spacing between elements?",
        "spacing" => "spacing",
        "margin" => "margin",
        "padding" => "padding",
        "gap" => "gap",
        
        // ========== JAVASCRIPT QUESTIONS ==========
        "Which company developed JavaScript?" => "Which company developed JavaScript?",
        "Microsoft" => "Microsoft",
        "Sun Microsystems" => "Sun Microsystems",
        "Netscape" => "Netscape",
        "Google" => "Google",
        "What is the correct way to write a comment in JavaScript?" => "What is the correct way to write a comment in JavaScript?",
        "// This is a comment" => "// This is a comment",
        "<!-- This is a comment -->" => "<!-- This is a comment -->",
        "# This is a comment" => "# This is a comment",
        "/* This is a comment */" => "/* This is a comment */",
        "Which function is used to print something to the console in JavaScript?" => "Which function is used to print something to the console in JavaScript?",
        "print()" => "print()",
        "console.print()" => "console.print()",
        "log.console()" => "log.console()",
        "console.log()" => "console.log()",
        "What does '===' operator do in JavaScript?" => "What does '===' operator do in JavaScript?",
        "Assignment" => "Assignment",
        "Comparison of values" => "Comparison of values",
        "Comparison of values and type" => "Comparison of values and type",
        "Not equal" => "Not equal",
        
        // ========== PHP QUESTIONS ==========
        "What does PHP stand for?" => "What does PHP stand for?",
        "Personal Home Page" => "Personal Home Page",
        "Preprocessor Hypertext" => "Preprocessor Hypertext",
        "Private Hosting Page" => "Private Hosting Page",
        "Professional Home Page" => "Professional Home Page",
        "How do you start a PHP session?" => "How do you start a PHP session?",
        "session_start()" => "session_start()",
        "start_session()" => "start_session()",
        "Session::start()" => "Session::start()",
        "session_begin()" => "session_begin()",
        "Which symbol is used to access a variable in PHP?" => "Which symbol is used to access a variable in PHP?",
        "$" => "$",
        "@" => "@",
        "#" => "#",
        "&" => "&",
        "What function is used to connect to MySQL database in PHP?" => "What function is used to connect to MySQL database in PHP?",
        "connect_mysql()" => "connect_mysql()",
        "db_connect()" => "db_connect()",
        "mysqli_connect()" => "mysqli_connect()",
        "mysql_connect()" => "mysql_connect()",
        
        // ========== MYSQL QUESTIONS ==========
        "What does SQL stand for?" => "What does SQL stand for?",
        "Structured Query Language" => "Structured Query Language",
        "Simple Query Language" => "Simple Query Language",
        "Style Query Language" => "Style Query Language",
        "Standard Query Language" => "Standard Query Language",
        "Which SQL statement is used to extract data from a database?" => "Which SQL statement is used to extract data from a database?",
        "EXTRACT" => "EXTRACT",
        "GET" => "GET",
        "SELECT" => "SELECT",
        "OPEN" => "OPEN",
        
        // ========== GENERAL PROGRAMMING ==========
        "What is Git used for?" => "What is Git used for?",
        "Version Control" => "Version Control",
        "Code Compilation" => "Code Compilation",
        "Database Management" => "Database Management",
        "Web Hosting" => "Web Hosting",
        "Which of the following is NOT a programming language?" => "Which of the following is NOT a programming language?",
        "Python" => "Python",
        "Java" => "Java",
        "HTML" => "HTML",
        "C++" => "C++",
        "select_difficulty" => "Select Difficulty Level",
"all_difficulties" => "All Difficulties",
"easy" => "Easy",
"medium" => "Medium",
"hard" => "Hard",
"available_questions" => "Available questions",
"quiz_setup" => "Quiz Setup",
"start_quiz" => "Start Quiz",
"new_quiz" => "New Quiz",
"difficulty" => "Difficulty",
"questions" => "Questions",
"explanations" => "Explanations",
"your_answer" => "Your answer",
"explanation_label" => "Explanation",
"high_scores" => "🏆 High Scores",
"total_attempts" => "Total Attempts",
"average_score" => "Average Score",
"highest_score" => "Highest Score",
"players" => "Players",
"player" => "Player",
"score" => "Score",
"percentage" => "Percentage",
"difficulty" => "Difficulty",
"date" => "Date",
"all" => "All",
"no_scores_yet" => "No scores yet! Be the first to play!",
"be_first" => "Be the First!",
"your_personal_best" => "Your Personal Best",
"max_score" => "max",
"audience" => "Audience",
"audience_help" => "Audience Help",
"close" => "Close",
"add_question" => "Add Question",
"edit_question" => "Edit Question",
"save_changes" => "Save Changes",
"cancel" => "Cancel",
"edit" => "Edit",
"no_questions_yet" => "No questions yet. Add your first question!",
    ],
    "hy" => [
        // ========== MAIN TRANSLATIONS ==========
        "title" => "Ծրագրավորման Քուիզ",
        "desc" => "Ստուգիր քո ծրագրավորման գիտելիքները!",
        "start" => "Սկսել խաղը",
        "admin" => "Ադմին պանել",
        "quiz_finished" => "Խաղն ավարտվեց",
        "great_job" => "Գերազանց աշխատանք 👍",
        "back_home" => "Գլխավոր էջ",
        "play_again" => "Կրկին խաղալ",
        "submit" => "Ուղարկել",
        "Admin Panel" => "Ադմինիստրատորի Պանել",
        "Add New Question" => "Ավելացնել նոր հարց",
        "Question" => "Հարց",
        "Option A" => "Տարբերակ A",
        "Option B" => "Տարբերակ B",
        "Option C" => "Տարբերակ C",
        "Option D" => "Տարբերակ D",
        "Correct Answer (1-4)" => "Ճիշտ պատասխան (1-4)",
        "existing_questions" => "Գոյություն ունեցող հարցեր",
        "correct_answer" => "Ճիշտ պատասխան",
        "delete" => "Ջնջել",
        "delete_confirm" => "Համոզված եք, որ ցանկանում եք ջնջել այս հարցը",
        
        // ========== AUTH TRANSLATIONS ==========
        "login" => "Մուտք",
        "register" => "Գրանցում",
        "logout" => "Ելք",
        "username" => "Օգտանուն",
        "email" => "Էլ. հասցե",
        "password" => "Գաղտնաբառ",
        "confirm_password" => "Հաստատել գաղտնաբառը",
        "already_have_account" => "Արդեն ունե՞ք հաշիվ",
        "login_here" => "Մուտք գործեք",
        "no_account" => "Չունե՞ք հաշիվ",
        "register_here" => "Գրանցվեք այստեղ",
        "username_or_email" => "Օգտանուն կամ Էլ. հասցե",
        "all_fields_required" => "Բոլոր դաշտերը պարտադիր են",
        "username_min_length" => "Օգտանունը պետք է լինի առնվազն 3 նիշ",
        "invalid_email" => "Սխալ էլ. հասցե",
        "password_min_length" => "Գաղտնաբառը պետք է լինի առնվազն 6 նիշ",
        "passwords_not_match" => "Գաղտնաբառերը չեն համապատասխանում",
        "username_or_email_exists" => "Օգտանունը կամ էլ. հասցեն արդեն գոյություն ունի",
        "registration_error" => "Գրանցման սխալ, փորձեք կրկին",
        "invalid_credentials" => "Սխալ օգտանուն/էլ. հասցե կամ գաղտնաբառ",
        "register_as_admin" => "Գրանցվել որպես Ադմին",
        "first_user_admin" => "🎯 Դուք առաջին օգտատերն եք: Դուք կգրանցվեք որպես ԱԴՄԻՆ",
        "admin_registered_success" => "Ադմինը հաջողությամբ գրանցվեց",
        "registered_success" => "Գրանցումը հաջողվեց",
        
        // ========== TIMER TRANSLATIONS ==========
        "total_time_left" => "⏰ Մնացած ժամանակ",
        "time_for_question" => "⏱️ Այս հարցի ժամանակը",
        "time_is_up" => "Ժամանակը վերջացավ",
        "timeout_message" => "Ցավոք, ձեր ժամանակը վերջացավ։ Խնդրում ենք կրկին փորձել։",
        
        // ========== PERCENTAGE & GRADES ==========
        "your_score_percentage" => "Ձեր արդյունքը",
        "excellent" => "Գերազանց!",
        "very_good" => "Շատ լավ!",
        "good" => "Լավ!",
        "average" => "Միջին",
        "poor" => "Պետք է աշխատել",
        "correct_answers" => "Ճիշտ պատասխաններ",
        "total_questions" => "Ընդհանուր հարցեր",
        "wrong_answers" => "Սխալ պատասխաններ",
        
        // ========== SHUFFLE & COUNT ==========
        "questions_shuffled" => "🎲 Հարցերը պատահական հերթականությամբ են",
        "reshuffle" => "🔄 Նորից խառնել հարցերը",
        "dark_mode" => "Մուգ ռեժիմ",
        "light_mode" => "Լույսի ռեժիմ",
        "select_question_count" => "Ընտրիր հարցերի քանակը",
        "playing_questions" => "Խաղում ես",
        "all_questions" => "Բոլոր հարցերը",
        
        // ========== HTML QUESTIONS ==========
        "What does HTML stand for?" => "Ի՞նչ է նշանակում HTML-ը:",
        "Hyper Text Markup Language" => "Հիպերտեքստի Մարկավորման Լեզու",
        "Home Tool Markup Language" => "Տնային Գործիքի Մարկավորման Լեզու",
        "Hyperlinks and Text Markup Language" => "Հիպերհղումների և Տեքստի Մարկավորման Լեզու",
        "High Tech Modern Language" => "Բարձր Տեխնոլոգիական Ժամանակակից Լեզու",
        "Which tag is used to create a hyperlink in HTML?" => "Ո՞ր թեգն է օգտագործվում HTML-ում հղում ստեղծելու համար:",
        "<link>" => "<link>",
        "<a>" => "<a>",
        "<href>" => "<href>",
        "<url>" => "<url>",
        "Which HTML tag is used to insert an image?" => "Ո՞ր HTML թեգն է օգտագործվում նկար տեղադրելու համար:",
        "<img>" => "<img>",
        "<table>" => "</td>",
        "<src>" => "<src>",
        "<pic>" => "<pic>",
        "What is the correct HTML element for the largest heading?" => "Ո՞րն է ամենամեծ վերնագրի ճիշտ HTML տարրը:",
        "<heading>" => "<heading>",
        "<h6>" => "<h6>",
        "<head>" => "<head>",
        "<h1>" => "<h1>",
        
        // ========== CSS QUESTIONS ==========
        "What does CSS stand for?" => "Ի՞նչ է նշանակում CSS-ը:",
        "Creative Style Sheets" => "Ստեղծագործական Ոճերի Թերթիկներ",
        "Computer Style Sheets" => "Համակարգչային Ոճերի Թերթիկներ",
        "Cascading Style Sheets" => "Կասկադային Ոճերի Թերթիկներ",
        "Colorful Style Sheets" => "Գունավոր Ոճերի Թերթիկներ",
        "Which CSS property is used to change the text color?" => "Ո՞ր CSS հատկությունն է օգտագործվում տեքստի գույնը փոխելու համար:",
        "text-color" => "text-color",
        "color" => "color",
        "font-color" => "font-color",
        "text-style" => "text-style",
        "How do you select an element with id 'header' in CSS?" => "Ինչպե՞ս ընտրել 'header' id-ով տարրը CSS-ում:",
        ".header" => ".header",
        "#header" => "#header",
        "header" => "header",
        "*header" => "*header",
        "Which CSS property controls the spacing between elements?" => "Ո՞ր CSS հատկությունն է վերահսկում տարրերի միջև հեռավորությունը:",
        "spacing" => "spacing",
        "margin" => "margin",
        "padding" => "padding",
        "gap" => "gap",
        
        // ========== JAVASCRIPT QUESTIONS ==========
        "Which company developed JavaScript?" => "Ո՞ր ընկերությունն է մշակել JavaScript-ը:",
        "Microsoft" => "Microsoft",
        "Sun Microsystems" => "Sun Microsystems",
        "Netscape" => "Netscape",
        "Google" => "Google",
        "What is the correct way to write a comment in JavaScript?" => "Ո՞րն է JavaScript-ում մեկնաբանություն գրելու ճիշտ տարբերակը:",
        "// This is a comment" => "// Սա մեկնաբանություն է",
        "<!-- This is a comment -->" => "<!-- Սա մեկնաբանություն է -->",
        "# This is a comment" => "# Սա մեկնաբանություն է",
        "/* This is a comment */" => "/* Սա մեկնաբանություն է */",
        "Which function is used to print something to the console in JavaScript?" => "Ո՞ր ֆունկցիան է օգտագործվում JavaScript-ում կոնսոլում ինչ-որ բան տպելու համար:",
        "print()" => "print()",
        "console.print()" => "console.print()",
        "log.console()" => "log.console()",
        "console.log()" => "console.log()",
        "What does '===' operator do in JavaScript?" => "Ի՞նչ է անում '===' օպերատորը JavaScript-ում:",
        "Assignment" => "Վերագրում",
        "Comparison of values" => "Արժեքների համեմատում",
        "Comparison of values and type" => "Արժեքների և տիպի համեմատում",
        "Not equal" => "Հավասար չէ",
        
        // ========== PHP QUESTIONS ==========
        "What does PHP stand for?" => "Ի՞նչ է նշանակում PHP-ն:",
        "Personal Home Page" => "Personal Home Page",
        "Preprocessor Hypertext" => "Նախապրոցեսոր Հիպերտեքստ",
        "Private Hosting Page" => "Private Hosting Page",
        "Professional Home Page" => "Professional Home Page",
        "How do you start a PHP session?" => "Ինչպե՞ս սկսել PHP սեսիա:",
        "session_start()" => "session_start()",
        "start_session()" => "start_session()",
        "Session::start()" => "Session::start()",
        "session_begin()" => "session_begin()",
        "Which symbol is used to access a variable in PHP?" => "Ո՞ր նշանն է օգտագործվում PHP-ում փոփոխականին հասանելիության համար:",
        "$" => "$",
        "@" => "@",
        "#" => "#",
        "&" => "&",
        "What function is used to connect to MySQL database in PHP?" => "Ո՞ր ֆունկցիան է օգտագործվում PHP-ում MySQL տվյալների բազային միանալու համար:",
        "connect_mysql()" => "connect_mysql()",
        "db_connect()" => "db_connect()",
        "mysqli_connect()" => "mysqli_connect()",
        "mysql_connect()" => "mysql_connect()",
        
        // ========== MYSQL QUESTIONS ==========
        "What does SQL stand for?" => "Ի՞նչ է նշանակում SQL-ը:",
        "Structured Query Language" => "Կառուցվածքային Հարցումների Լեզու",
        "Simple Query Language" => "Պարզ Հարցումների Լեզու",
        "Style Query Language" => "Ոճերի Հարցումների Լեզու",
        "Standard Query Language" => "Ստանդարտ Հարցումների Լեզու",
        "Which SQL statement is used to extract data from a database?" => "Ո՞ր SQL հայտարարությունն է օգտագործվում տվյալների բազայից տվյալներ հանելու համար:",
        "EXTRACT" => "EXTRACT",
        "GET" => "GET",
        "SELECT" => "SELECT",
        "OPEN" => "OPEN",
        
        // ========== GENERAL PROGRAMMING ==========
        "What is Git used for?" => "Ինչի՞ համար է օգտագործվում Git-ը:",
        "Version Control" => "Տարբերակների վերահսկում",
        "Code Compilation" => "Կոդի կոմպիլացիա",
        "Database Management" => "Տվյալների բազայի կառավարում",
        "Web Hosting" => "Վեբ հոսթինգ",
        "Which of the following is NOT a programming language?" => "Հետևյալներից ո՞րը ԾՐԱԳՐԱՎՈՐՄԱՆ ԼԵԶՈՒ ՉԷ:",
        "Python" => "Python",
        "Java" => "Java",
        "HTML" => "HTML",
        "C++" => "C++",
        "select_difficulty" => "Ընտրիր դժվարության մակարդակը",
"all_difficulties" => "Բոլոր դժվարությունները",
"easy" => "Հեշտ",
"medium" => "Միջին",
"hard" => "Դժվար",
"available_questions" => "Հասանելի հարցեր",
// hy
"quiz_setup" => "Քուիզի կարգավորում",
"start_quiz" => "Սկսել քուիզը",
"new_quiz" => "Նոր քուիզ",
"difficulty" => "Դժվարություն",
"questions" => "Հարցեր",
"explanations" => "Բացատրություններ",
"your_answer" => "Ձեր պատասխանը",
"explanation_label" => "Բացատրություն",
// hy
"high_scores" => "🏆 Լավագույն Արդյունքներ",
"total_attempts" => "Ընդհանուր փորձեր",
"average_score" => "Միջին միավոր",
"highest_score" => "Ամենաբարձր միավոր",
"players" => "Խաղացողներ",
"player" => "Խաղացող",
"score" => "Միավոր",
"percentage" => "Տոկոս",
"difficulty" => "Դժվարություն",
"date" => "Ամսաթիվ",
"all" => "Բոլորը",
"no_scores_yet" => "Դեռ արդյունքներ չկան։ Եղիր առաջինը!",
"be_first" => "Եղիր Առաջինը!",
"your_personal_best" => "Ձեր լավագույն արդյունքը",
"max_score" => "առավելագույնը",
"audience" => "Հանդիսատես",
"audience_help" => "Հանդիսատեսի օգնություն",
"close" => "Փակել",
// hy
"add_question" => "Ավելացնել Հարց",
"edit_question" => "Խմբագրել Հարցը",
"save_changes" => "Պահպանել Փոփոխությունները",
"cancel" => "Չեղարկել",
"edit" => "Խմբագրել",
"no_questions_yet" => "Դեռ հարցեր չկան։ Ավելացրու քո առաջին հարցը։",
    ]
];

// ՀԻՄՆԱԿԱՆ ՏԵՔՍՏԵՐԻ ՖՈՒՆԿՑԻԱՆ (առանց ավտոմատ թարգմանության)
function t($key){
    global $texts, $lang;
    
    // 1. Եթե բառը կա զանգվածում, վերցրու այնտեղից
    if (isset($texts[$lang][$key])) {
        return $texts[$lang][$key];
    }
    
    // 2. Եթե չկա, ցույց տուր key-ը
    return $key;
}
?>